In [2]:
import numpy as np

In [4]:
new_array = np.arange(12)
new_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
new_array[8]

8

In [6]:
new_array[-3]

9

In [7]:
new_array[::]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
new_array[::2]

array([ 0,  2,  4,  6,  8, 10])

In [9]:
new_array[:8:2]

array([0, 2, 4, 6])

In [11]:
d_array = new_array.reshape(3,4)
d_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
d_array[:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
d_array[0,:]

array([0, 1, 2, 3])

In [19]:
d_array[:,2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [23]:
array_m = np.linspace(10,100,10)
array_m

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [29]:
array_rand = np.random.random(9).reshape(3,3)
array_rand

array([[0.08210469, 0.14780855, 0.84321153],
       [0.01209361, 0.6833092 , 0.86940009],
       [0.85794446, 0.21000855, 0.89262253]])

In [42]:
# Display forst 2 rows
array_rand[:2]

array([[0.08210469, 0.14780855, 0.84321153],
       [0.01209361, 0.6833092 , 0.86940009]])

In [41]:
# display frst row
array_rand[:,0]

array([0.08210469, 0.01209361, 0.85794446])

In [40]:
# 2nd number in 3rd row
array_rand[2,1]

0.21000854821558845