In [1]:
import numpy as np

First, add a flat shipping cost of 5 to our prices to get the 
‘total’ amount owed.
The numbers in the random array represent ‘discount 
percent’. To get the ‘percent owed’, subtract the first 6 
numbers in the random array from 1, then multiply ‘percent 
owed’ by ‘total’ to get the final amount owed.

In [2]:
prices = np.array([5.99,6.99,22.49,99.99,4.99,49.99])
total = prices + 5
total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [5]:
discount_pct = np.random.random(6)
discount_pct

array([0.29867486, 0.53275348, 0.58415866, 0.51642468, 0.46834711,
       0.62982216])

In [6]:
percent_owed = 1 - discount_pct
percent_owed

array([0.70132514, 0.46724652, 0.41584134, 0.48357532, 0.53165289,
       0.37017784])

In [7]:
percent_owed * total

array([ 7.70756325,  5.60228583, 11.43147849, 50.77057333,  5.31121237,
       20.35607952])