In [1]:
import numpy as np

In [2]:
np.ones(2)

array([1., 1.])

In [3]:
array_zero=np.zeros((2,3),float)

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.linspace(100,200,5)

array([100., 125., 150., 175., 200.])

In [6]:
array_zero.reshape(3,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
#array creation using random number generator
from numpy.random import default_rng

rng = default_rng(12345)
array_new = rng.random(20)
array_new

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287,
       0.24824571, 0.94888115, 0.66723745, 0.09589794, 0.44183967,
       0.88647992, 0.6974535 , 0.32647286, 0.73392816, 0.22013496])

In [13]:
# Create an array and reshape to 5 x 2
new_array = np.linspace(10,100,10).reshape(5,2)
new_array

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

In [17]:
# create an array of random numbers between 0 and 1 in a 3x3 shape. 
rng1 = default_rng(456)
array1 = rng1.random(9).reshape(3,3)
array1

array([[0.46967324, 0.4476553 , 0.12405681],
       [0.75484998, 0.97298845, 0.0830198 ],
       [0.30430819, 0.79605268, 0.40109078]])